version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: analyzer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/analyzer
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata:
